cloud:
  aws:
    credentials:
      access-key: empty
      secret-key: empty
    region:
      static: ap-south-1
    stack:
      auto: false
application:
  bucket:
    name: sample-textextract

server:
  port: 9090
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB